// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington UW CoMotion, email: license@uw.edu.

/// @file    core/chemical/ResidueProperty.hh
/// @brief   Enumeration definition for ResidueProperty.
/// @author  Labonte <JWLabonte@jhu.edu>
/// @note    DO NOT EDIT THIS FILE DIRECTLY!  It is auto-generated.
/// If you wish to edit it, modify the update_ResidueType_enum_files.py script.

#ifndef INCLUDED_core_chemical_ResidueProperty_HH
#define INCLUDED_core_chemical_ResidueProperty_HH

namespace core {
namespace chemical {

// If adding a new property, DO NOT MANUALLY EDIT THIS ENUMERATOR DEFINITION.
// Instead, add it to general_properties.list, and run the update_ResidueType_enum_files.py script.
/// @brief   Enumerators for all the properties that can be assigned to a ResidueType.
enum ResidueProperty {
	NO_PROPERTY = 0,
	FIRST_PROPERTY = 1,
	POLYMER = 1,
	LIGAND,
	PROTEIN,  // TODO: Change this to AMINO_ACID, since that's what it really means. ~Labonte
	CANONICAL_AA,
	CANONICAL_NUCLEIC,
	DNA,
	RNA,
	PNA,
	PEPTOID,
	CARBOHYDRATE,
	LIPID,
	TERPENE,
	SRI,  // New class of artificial heteropolymers. ~VMulligan
	TRIAZOLE_LINKER,  // Another new class of artificial heteropolymers. ~Vmulligan
	METAL,  // This residue type is a metal ion.
	SURFACE,
	WATER,
	SOLVENT,
	VIRTUAL_RESIDUE,
	INVERTED_VIRTUAL_RESIDUE,  //Used by the symmetry machinery for mirror symmetry. ~Vmulligan
	TERMINUS,
	UPPERTERM_CAP,
	LOWERTERM_CAP,
	LOWER_TERMINUS,  // first residue in a chain
	UPPER_TERMINUS,  // last residue in a chain
	BRANCH_LOWER_TERMINUS,
	BRANCH_POINT,
	LOWERTERM_TRUNC,
	UPPERTERM_TRUNC,
	COARSE,  // currently for coarse_RNA only
	ADDUCT,
	SC_ORBITALS,
	FRAGMENT,  // shows up in GrowLigand
	POLAR,  //This is for clearly polar side-chains (DEHKNQRST).  Note that it excludes glycine, alanine, cysteine, and proline (as well as very hydrophobic residues with polar groups, like tryptophan or tyrosine).
	HYDROPHOBIC,  //This is for clearly hydrophobic side-chains (FMILYVW).  Note that it also excludes glycine, alanine, cysteine, and proline.  The union of POLAR and HYDROPHOBIC does NOT include all amino acids.
	CHARGED,
	NEGATIVE_CHARGE,  //Has a negative charge.  Includes zwitterionic side-chains.
	POSITIVE_CHARGE,  //Has a positive charge.  Includes zwitterionic side-chains.
	AROMATIC,
	ALIPHATIC,  //Has a side-chain (i.e. not gly) and the side-chain contains only carbon and hydrogen, with no aromatic rings.  Methionine is included as an "honourary" aliphatic, so the set is: ALA, VAL, ILE, LEU, PRO, MET.
	CYCLIC,
	METALBINDING,  // This residue type is a one capable of binding to a metal ion.
	SIDECHAIN_THIOL,  // This residue type is capable of forming a disulfide bond
	DISULFIDE_BONDED,  // This residue type contains a disulfide bond/noncanonical connection
	ELECTROPHILE,  // This residue type has a side-chain that can be conjugated to a nucleophile (for example, it contains an alpha-beta unsaturated carbonyl)
	SIDECHAIN_AMINE,
	N_METHYLATED,  // A methyl group replaces the amide proton in residues in the MIDDLE of a sequence (not at the N-terminus)
	MEMBRANE,
	PHOSPHONATE,  // amino phosphonic acid instead of amino carboxylic acid
	PHOSPHONATE_UPPER,
	ACETYLATED_NTERMINUS,
	METHYLATED_CTERMINUS,
	ALPHA_AA,
	BETA_AA,
	GAMMA_AA,
	L_AA,  //Chirality.  This is defined as the chirality of the first chiral mainchain atom closest to the LOWER_CONNECT -- so a trisubstituted 2D,3D,4L-gamma-amino acid would be considered an L_AA.
	D_AA,  //Chirality.  This is defined as the chirality of the first chiral mainchain atom closest to the LOWER_CONNECT -- so a trisubstituted 2L,3L,4D-gamma-amino acid would be considered a D_AA.
	ACHIRAL_BACKBONE,
	TAUTOMER,
	PURINE,
	PYRIMIDINE,
	L_RNA,
	D_RNA,
	TRIOSE,
	TETROSE,
	PENTOSE,
	HEXOSE,
	HEPTOSE,
	OCTOSE,
	NONOSE,
	ALDOSE,
	KETOSE,
	L_SUGAR,
	D_SUGAR,
	OXIROSE,
	OXETOSE,
	FURANOSE,
	PYRANOSE,
	SEPTANOSE,
	ALPHA_SUGAR,
	BETA_SUGAR,
	SIALIC_ACID,
	C1_MODIFIED,  // for any saccharide residue modified at the 1 position
	C2_MODIFIED,  // for any saccharide residue modified at the 2 position
	C3_MODIFIED,  // for any saccharide residue modified at the 3 position
	C4_MODIFIED,  // for any saccharide residue modified at the 4 position
	C5_MODIFIED,  // for any saccharide residue modified at the 5 position
	C6_MODIFIED,  // for any saccharide residue modified at the 6 position
	C7_MODIFIED,  // for any saccharide residue modified at the 7 position
	C8_MODIFIED,  // for any saccharide residue modified at the 8 position
	C9_MODIFIED,  // for any saccharide residue modified at the 9 position
	GLYCOSIDE,
	ALDONIC_ACID,
	URONIC_ACID,
	DEOXY_SUGAR,
	AMINO_SUGAR,
	ACETYLAMINO_SUGAR,  // specific for N-acetylations
	ACETYL_SUGAR,  // specific for O-acetylations
	R3PRIMEHYDROXYBUTYRYLAMINO_SUGAR,
	SULFATED_SUGAR,
	SULFOAMINO_SUGAR,
	C_METHYLATED_SUGAR,
	PHOSPHATE,
	N_PROPERTIES = PHOSPHATE
};

}  // namespace chemical
}  // namespace core

#endif  // INCLUDED_core_chemical_ResidueProperty_HH
