// -*- mode:c++;tab-width:2;indent-tabs-mode:t;show-trailing-whitespace:t;rm-trailing-spaces:t -*-
// vi: set ts=2 noet:
//
// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington CoMotion, email: license@uw.edu.

/// @file   utility/version.hh
///
/// @brief
/// @author Sergey Lyskov

/*****************************************************************************
*   This file is automatically generated by the build system.                *
*   DO NOT try modifying it by hand -- your changes will be lost.            *
*   DO NOT commit it to the Git repository.                                  *
*****************************************************************************/

#ifndef INCLUDED_utility_version_hh
#define INCLUDED_utility_version_hh

#include <string>

namespace utility {

struct Version
{
    static std::string commit_id() { return "unknown"; }
    static std::string commit()    { return "exported"; }
    static std::string url()       { return "http://www.rosettacommons.org"; }
    static std::string date()      { return ""; }
};

} // utility
#endif // INCLUDED_utility_version_hh
